name: Deployment Pipeline

on:
  push:
    branches:
      - master
      - development

jobs:
  validate-and-migrate:
    name: Validate and Migrate
    runs-on: ubuntu-latest
    environment:
      name: ${{ (github.ref == 'refs/heads/master' && 'Production') || 'Development' }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Run Backend Tests
        run: npm run test

      - name: Run Migrations on Master
        if: github.ref == 'refs/heads/master'
        run: npx prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Run Migrations on Development
        if: github.ref == 'refs/heads/development'
        run: npx prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
